<%@ Page Title="Caselle di posta" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CasellePostali.aspx.cs" Inherits="WebGestPersV2.Personale.CasellePostali" MaintainScrollPositionOnPostback="true" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Caselle di posta</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <asp:HyperLink ID="BackLink" runat="server" CssClass="back-link">← Torna al dettaglio</asp:HyperLink>
 <div class="page-heading"><p class="eyebrow"><asp:Literal ID="PersonnelType" runat="server"/></p><h1>Caselle di posta di <asp:Literal ID="FullName" runat="server"/></h1><p>Gestione degli indirizzi personali, funzionali e condivisi associati al dipendente.</p></div>
 <asp:Label ID="Message" runat="server" CssClass="message error" Visible="false"/>
 <section class="card"><h2>Caselle associate</h2><asp:GridView ID="MailboxesGrid" runat="server" AutoGenerateColumns="false" DataKeyNames="Id" CssClass="data-grid" GridLines="None" EmptyDataText="Nessuna casella postale associata." OnRowCommand="MailboxesGrid_RowCommand"><Columns>
  <asp:BoundField DataField="Denominazione" HeaderText="Indirizzo e-mail"/><asp:BoundField DataField="Tipo" HeaderText="Tipo"/><asp:TemplateField HeaderText="Azioni"><ItemTemplate><asp:LinkButton runat="server" CommandName="ModificaCasella" CommandArgument='<%# Eval("Id") %>' Text="Modifica" CssClass="grid-action"/><span> · </span><asp:LinkButton runat="server" CommandName="EliminaCasella" CommandArgument='<%# Eval("Id") %>' Text="Elimina" CssClass="grid-action danger" OnClientClick="return confirm('Eliminare la casella postale selezionata?');"/></ItemTemplate></asp:TemplateField>
 </Columns></asp:GridView></section>
 <section class="card form-card detail-section"><h2><asp:Literal ID="FormTitle" runat="server" Text="Aggiungi casella postale"/></h2><asp:ValidationSummary runat="server" CssClass="message error" ValidationGroup="mailbox"/><div class="edit-grid">
  <label>Indirizzo e-mail*</label><asp:TextBox ID="EmailAddress" runat="server" MaxLength="255" TextMode="Email" AutoPostBack="true" OnTextChanged="EmailAddress_Changed"/><asp:RequiredFieldValidator runat="server" ControlToValidate="EmailAddress" ErrorMessage="Indirizzo e-mail obbligatorio." ValidationGroup="mailbox" CssClass="field-error"/>
  <label>Tipo*</label><asp:DropDownList ID="MailboxType" runat="server"><asp:ListItem Value="personale">Personale</asp:ListItem><asp:ListItem Value="funzionale">Funzionale</asp:ListItem><asp:ListItem Value="funzionale (sec)">Funzionale (sec)</asp:ListItem><asp:ListItem Value="condivisa">Condivisa</asp:ListItem></asp:DropDownList><span class="field-hint">Le caselle funzionali e condivise possono essere associate a più persone.</span>
 </div><div class="form-actions"><asp:Button ID="VerifyButton" runat="server" Text="Verifica disponibilità" CssClass="button secondary" ValidationGroup="mailbox" OnClick="VerifyButton_Click"/><asp:Button ID="SaveButton" runat="server" Text="Aggiungi" CssClass="button" ValidationGroup="mailbox" OnClick="SaveButton_Click"/><asp:Button ID="CancelEditButton" runat="server" Text="Annulla modifica" CssClass="button secondary" CausesValidation="false" Visible="false" OnClick="CancelEditButton_Click"/></div>
 <asp:Label ID="DetectedTypeMessage" runat="server" CssClass="field-hint" Visible="false"/>
 <asp:Panel ID="AssignmentAlert" runat="server" CssClass="message error" Visible="false"><strong>Casella già assegnata.</strong><p>La casella risulta associata alle seguenti persone:</p><asp:GridView ID="AssignedPeopleGrid" runat="server" AutoGenerateColumns="false" CssClass="data-grid" GridLines="None"><Columns><asp:BoundField DataField="Assegnatario" HeaderText="Assegnatario"/><asp:BoundField DataField="Tipo" HeaderText="Tipo"/></Columns></asp:GridView><p>Confermando il trasferimento, tutte le precedenti associazioni di questo indirizzo saranno rimosse.</p><asp:Button ID="TransferButton" runat="server" Text="Trasferisci e assegna" CssClass="button" ValidationGroup="mailbox" OnClick="TransferButton_Click" OnClientClick="return confirm('Confermare il trasferimento? La casella sarà rimossa dagli utenti indicati e assegnata alla persona corrente.');"/></asp:Panel>
 <asp:Label ID="AvailabilityMessage" runat="server" CssClass="message info" Visible="false"/>
 </section>
</asp:Content>
