<%@ Page Title="Report caselle postali" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="CasellePostali.aspx.cs" Inherits="WebGestPersV2.Report.CasellePostali" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Report caselle postali</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Indice.aspx">← Torna ai report</a><div class="page-heading"><p class="eyebrow">Posta elettronica</p><h1>Caselle postali del personale</h1><p>Vista unificata delle caselle associate al personale militare e civile, con controlli su dominio, assegnazioni multiple e personale attivo senza casella.</p></div>
 <asp:Label ID="Message" runat="server" CssClass="message error" Visible="false"/>
 <section class="report-kpis"><div class="card"><span>Indirizzi distinti</span><strong><asp:Literal ID="DistinctAddresses" runat="server"/></strong></div><div class="card"><span>Associazioni</span><strong><asp:Literal ID="Associations" runat="server"/></strong></div><div class="card"><span>Assegnazioni multiple</span><strong><asp:Literal ID="MultipleAddresses" runat="server"/></strong></div><div class="card"><span>Anomalie dominio</span><strong><asp:Literal ID="DomainAnomalies" runat="server"/></strong></div><div class="card"><span>Attivi senza casella</span><strong><asp:Literal ID="WithoutMailbox" runat="server"/></strong></div></section>
 <section class="card detail-section"><h2>Filtri</h2><div class="people-filters">
  <div><label for="MainContent_SearchText">Ricerca</label><asp:TextBox ID="SearchText" runat="server"/></div><div><label for="MainContent_PersonnelType">Personale</label><asp:DropDownList ID="PersonnelType" runat="server"><asp:ListItem Value="">Tutto</asp:ListItem><asp:ListItem Value="M">Militare</asp:ListItem><asp:ListItem Value="C">Civile</asp:ListItem></asp:DropDownList></div>
  <div><label for="MainContent_ServiceStatus">Stato</label><asp:DropDownList ID="ServiceStatus" runat="server"><asp:ListItem Value="attivo">Attivo</asp:ListItem><asp:ListItem Value="">Tutti</asp:ListItem><asp:ListItem Value="nonattivo">Non attivo</asp:ListItem></asp:DropDownList></div>
  <div><label for="MainContent_MailboxType">Tipo casella</label><asp:DropDownList ID="MailboxType" runat="server"><asp:ListItem Value="">Tutti</asp:ListItem><asp:ListItem Value="personale">Personale</asp:ListItem><asp:ListItem Value="funzionale">Funzionale</asp:ListItem><asp:ListItem Value="funzionale (sec)">Funzionale (sec)</asp:ListItem><asp:ListItem Value="condivisa">Condivisa</asp:ListItem></asp:DropDownList></div>
  <div><label for="MainContent_QuickView">Vista rapida</label><asp:DropDownList ID="QuickView" runat="server"><asp:ListItem Value="">Tutte</asp:ListItem><asp:ListItem Value="multiple">Assegnazioni multiple</asp:ListItem><asp:ListItem Value="anomalie">Anomalie dominio</asp:ListItem><asp:ListItem Value="nonattivi">Personale non attivo</asp:ListItem></asp:DropDownList></div>
 </div><div class="form-actions"><asp:Button ID="ApplyFilters" runat="server" Text="Applica filtri" CssClass="button" OnClick="ApplyFilters_Click"/><asp:Button ID="ResetFilters" runat="server" Text="Azzera" CssClass="button secondary" OnClick="ResetFilters_Click"/><asp:Button ID="ExportExcel" runat="server" Text="Esporta Excel" CssClass="button secondary" OnClick="ExportExcel_Click"/></div></section>
 <section class="card detail-section report-wide"><h2>Associazioni persona-casella</h2><asp:Label ID="ResultCount" runat="server" CssClass="result-count"/><asp:GridView ID="MailboxesGrid" runat="server" AutoGenerateColumns="false" CssClass="data-grid" GridLines="None" EmptyDataText="Nessuna associazione trovata."><Columns><asp:BoundField DataField="Indirizzo" HeaderText="Indirizzo"/><asp:BoundField DataField="Tipo" HeaderText="Tipo"/><asp:HyperLinkField DataTextField="Cognome" HeaderText="Cognome" DataNavigateUrlFields="IdPersonale" DataNavigateUrlFormatString="../Personale/Dettaglio.aspx?id={0}"/><asp:BoundField DataField="Nome" HeaderText="Nome"/><asp:BoundField DataField="TipoPersonale" HeaderText="Personale"/><asp:BoundField DataField="GradoProfilo" HeaderText="Grado/Profilo"/><asp:BoundField DataField="StatoServizio" HeaderText="Stato"/><asp:BoundField DataField="Ufficio1" HeaderText="Ufficio 1°"/><asp:BoundField DataField="Ufficio2" HeaderText="Ufficio 2°"/><asp:BoundField DataField="Ufficio3" HeaderText="Ufficio 3°"/><asp:BoundField DataField="NumeroAssegnatari" HeaderText="Assegnatari"/><asp:BoundField DataField="Coerenza" HeaderText="Controllo dominio"/></Columns></asp:GridView></section>
 <section class="card detail-section"><h2>Personale attivo senza casella</h2><p class="field-hint">Persone attive prive di qualsiasi associazione in Cassette_Postali.</p><asp:GridView ID="WithoutMailboxGrid" runat="server" AutoGenerateColumns="false" CssClass="data-grid" GridLines="None" EmptyDataText="Nessun nominativo privo di casella." OnRowDataBound="WithoutMailboxGrid_RowDataBound"><Columns><asp:HyperLinkField DataTextField="Cognome" HeaderText="Cognome" DataNavigateUrlFields="IdPersonale" DataNavigateUrlFormatString="../Personale/Dettaglio.aspx?id={0}"/><asp:BoundField DataField="Nome" HeaderText="Nome"/><asp:BoundField DataField="TipoPersonale" HeaderText="Personale"/><asp:BoundField DataField="GradoProfilo" HeaderText="Grado/Profilo"/><asp:BoundField DataField="Incarico" HeaderText="Incarico"/><asp:BoundField DataField="Ufficio1" HeaderText="Ufficio 1°"/><asp:TemplateField HeaderText="Azioni"><ItemTemplate><asp:HyperLink ID="ManageMailboxLink" runat="server" Text="Gestisci" NavigateUrl='<%# "../Personale/CasellePostali.aspx?id=" + Eval("IdPersonale") %>'/></ItemTemplate></asp:TemplateField></Columns></asp:GridView></section>
</asp:Content>
