using System;using System.Collections.Generic;using System.IO;using System.IO.Compression;using System.Linq;using System.Text;using System.Xml;using WebGestPersV2.Data;using WebGestPersV2.Models;
namespace WebGestPersV2.Report
{
 public partial class CasellePostali:Security.BaseAuthenticatedPage
 {
  protected override int[] LivelliConsentiti{get{return new[]{140,150,160,170,200};}}
  private CasellePostaliReportRepository Repository{get{return new CasellePostaliReportRepository();}}
  protected void Page_Load(object s,EventArgs e){if(!IsPostBack)Carica();}
  protected void ApplyFilters_Click(object s,EventArgs e){Carica();}
  protected void ResetFilters_Click(object s,EventArgs e){SearchText.Text="";PersonnelType.SelectedValue="";ServiceStatus.SelectedValue="attivo";MailboxType.SelectedValue="";QuickView.SelectedValue="";Carica();}
  protected void WithoutMailboxGrid_RowDataBound(object sender,System.Web.UI.WebControls.GridViewRowEventArgs e){if(e.Row.RowType!=System.Web.UI.WebControls.DataControlRowType.DataRow)return;var x=e.Row.DataItem as PersonaSenzaCasellaItem;var link=e.Row.FindControl("ManageMailboxLink") as System.Web.UI.WebControls.HyperLink;if(x==null||link==null)return;int l=UtenteCorrente.Livello;link.Visible=l==200||l==170||(x.Militare&&l==150)||(!x.Militare&&l==160);}
  private void Carica(){try{IList<CasellaPostaleReportItem> tutti=Repository.Elenca();IList<PersonaSenzaCasellaItem> senza=Repository.SenzaCasella();AggiornaIndicatori(tutti,senza);IList<CasellaPostaleReportItem> dati=Filtra(tutti);MailboxesGrid.DataSource=dati;MailboxesGrid.DataBind();WithoutMailboxGrid.DataSource=FiltraSenza(senza);WithoutMailboxGrid.DataBind();ResultCount.Text=dati.Count+" associazioni visualizzate";Message.Visible=false;}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
  private IList<CasellaPostaleReportItem> Filtra(IList<CasellaPostaleReportItem> dati){IEnumerable<CasellaPostaleReportItem> q=dati;string cerca=(SearchText.Text??"").Trim();if(cerca.Length>0)q=q.Where(x=>Contiene(x.Indirizzo,cerca)||Contiene(x.Cognome,cerca)||Contiene(x.Nome,cerca)||Contiene(x.Ufficio1,cerca)||Contiene(x.Ufficio2,cerca)||Contiene(x.Ufficio3,cerca));if(PersonnelType.SelectedValue=="M")q=q.Where(x=>x.Militare);if(PersonnelType.SelectedValue=="C")q=q.Where(x=>!x.Militare);if(ServiceStatus.SelectedValue=="attivo")q=q.Where(x=>Uguale(x.StatoServizio,"attivo"));if(ServiceStatus.SelectedValue=="nonattivo")q=q.Where(x=>!Uguale(x.StatoServizio,"attivo"));if(MailboxType.SelectedValue!="")q=q.Where(x=>Uguale(x.Tipo,MailboxType.SelectedValue));if(QuickView.SelectedValue=="multiple")q=q.Where(x=>x.NumeroAssegnatari>1);if(QuickView.SelectedValue=="anomalie")q=q.Where(x=>!x.CoerenteDominio);if(QuickView.SelectedValue=="nonattivi")q=q.Where(x=>!Uguale(x.StatoServizio,"attivo"));return q.ToList();}
  private IList<PersonaSenzaCasellaItem> FiltraSenza(IList<PersonaSenzaCasellaItem> dati){IEnumerable<PersonaSenzaCasellaItem> q=dati;if(PersonnelType.SelectedValue=="M")q=q.Where(x=>x.Militare);if(PersonnelType.SelectedValue=="C")q=q.Where(x=>!x.Militare);string cerca=(SearchText.Text??"").Trim();if(cerca.Length>0)q=q.Where(x=>Contiene(x.Cognome,cerca)||Contiene(x.Nome,cerca)||Contiene(x.Ufficio1,cerca)||Contiene(x.Ufficio2,cerca)||Contiene(x.Ufficio3,cerca));return q.ToList();}
  private void AggiornaIndicatori(IList<CasellaPostaleReportItem> x,IList<PersonaSenzaCasellaItem> s){DistinctAddresses.Text=x.Select(i=>(i.Indirizzo??"").Trim().ToLowerInvariant()).Distinct().Count().ToString();Associations.Text=x.Count.ToString();MultipleAddresses.Text=x.Where(i=>i.NumeroAssegnatari>1).Select(i=>(i.Indirizzo??"").Trim().ToLowerInvariant()).Distinct().Count().ToString();DomainAnomalies.Text=x.Count(i=>!i.CoerenteDominio).ToString();WithoutMailbox.Text=s.Count.ToString();}
  protected void ExportExcel_Click(object s,EventArgs e){try{var a=Filtra(Repository.Elenca());var w=FiltraSenza(Repository.SenzaCasella());byte[] file=CreaExcel(a,w);Response.Clear();Response.Buffer=true;Response.ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";Response.AddHeader("Content-Disposition","attachment; filename=Report_Caselle_Postali_"+DateTime.Today.ToString("yyyyMMdd")+".xlsx");Response.BinaryWrite(file);Response.Flush();Context.ApplicationInstance.CompleteRequest();}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
  private static byte[] CreaExcel(IList<CasellaPostaleReportItem> a,IList<PersonaSenzaCasellaItem> w){using(var m=new MemoryStream()){using(var z=new ZipArchive(m,ZipArchiveMode.Create,true)){Testo(z,"[Content_Types].xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet2.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");Testo(z,"_rels/.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");Testo(z,"xl/workbook.xml","<?xml version=\"1.0\" encoding=\"UTF-8\"?><workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"Associazioni\" sheetId=\"1\" r:id=\"rId1\"/><sheet name=\"Senza casella\" sheetId=\"2\" r:id=\"rId2\"/></sheets></workbook>");Testo(z,"xl/_rels/workbook.xml.rels","<?xml version=\"1.0\" encoding=\"UTF-8\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet2.xml\"/></Relationships>");Foglio(z,"xl/worksheets/sheet1.xml",Righe(a));Foglio(z,"xl/worksheets/sheet2.xml",Righe(w));}return m.ToArray();}}
  private static IEnumerable<string[]> Righe(IList<CasellaPostaleReportItem> x){yield return new[]{"Indirizzo","Tipo","ID","Cognome","Nome","Personale","Grado/Profilo","Stato","Forza armata","Categorico","Incarico","Ufficio 1","Ufficio 2","Ufficio 3","Assegnatari","Controllo dominio"};foreach(var i in x)yield return new[]{i.Indirizzo,i.Tipo,i.IdPersonale.ToString(),i.Cognome,i.Nome,i.TipoPersonale,i.GradoProfilo,i.StatoServizio,i.ForzaArmata,i.Categorico,i.Incarico,i.Ufficio1,i.Ufficio2,i.Ufficio3,i.NumeroAssegnatari.ToString(),i.Coerenza};}
  private static IEnumerable<string[]> Righe(IList<PersonaSenzaCasellaItem> x){yield return new[]{"ID","Cognome","Nome","Personale","Grado/Profilo","Incarico","Ufficio 1","Ufficio 2","Ufficio 3"};foreach(var i in x)yield return new[]{i.IdPersonale.ToString(),i.Cognome,i.Nome,i.TipoPersonale,i.GradoProfilo,i.Incarico,i.Ufficio1,i.Ufficio2,i.Ufficio3};}
  private static void Testo(ZipArchive z,string n,string c){var e=z.CreateEntry(n,CompressionLevel.Fastest);using(var s=e.Open())using(var w=new StreamWriter(s,new UTF8Encoding(false)))w.Write(c);}private static void Foglio(ZipArchive z,string n,IEnumerable<string[]> righe){var e=z.CreateEntry(n,CompressionLevel.Fastest);using(var s=e.Open())using(var x=XmlWriter.Create(s,new XmlWriterSettings{Encoding=new UTF8Encoding(false)})){const string ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";x.WriteStartDocument();x.WriteStartElement("worksheet",ns);x.WriteStartElement("sheetData",ns);foreach(var r in righe){x.WriteStartElement("row",ns);foreach(var v in r){x.WriteStartElement("c",ns);x.WriteAttributeString("t","inlineStr");x.WriteStartElement("is",ns);x.WriteElementString("t",ns,v??"");x.WriteEndElement();x.WriteEndElement();}x.WriteEndElement();}x.WriteEndElement();x.WriteEndElement();x.WriteEndDocument();}}
  private static bool Contiene(string x,string y){return (x??"").IndexOf(y,StringComparison.OrdinalIgnoreCase)>=0;}private static bool Uguale(string x,string y){return string.Equals((x??"").Trim(),y,StringComparison.OrdinalIgnoreCase);}
 }
}
