<%@ Page Title="Composizione del personale" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<%@ Import Namespace="System.Collections.Generic" %><%@ Import Namespace="System.Configuration" %><%@ Import Namespace="System.Data.SqlClient" %>
<script runat="server">
 public sealed class VoceReport { public string Etichetta { get; set; } public int Conteggio { get; set; } public decimal Percentuale { get; set; } public string PercentualeTesto { get { return Percentuale.ToString("0.0")+"%"; } } public string Larghezza { get { return Percentuale.ToString("0.0",System.Globalization.CultureInfo.InvariantCulture)+"%"; } } }
 protected override void OnLoad(EventArgs e){base.OnLoad(e);if(!IsPostBack)Carica();}
 private void Carica(){try{Bind(Tipo,Leggi(@"SELECT CASE WHEN Militare=1 THEN 'Militare' ELSE 'Civile' END,COUNT(*) FROM dbo.ElencoPersonale WHERE Stato_Servizio='attivo' GROUP BY Militare"));Bind(Sesso,Leggi(@"SELECT CASE WHEN SessoM=1 THEN 'Uomini' ELSE 'Donne' END,COUNT(*) FROM dbo.ElencoPersonale WHERE Stato_Servizio='attivo' GROUP BY SessoM"));Bind(ForzaArmata,Leggi(@"SELECT RTRIM(f.SiglaArma),COUNT(*) FROM dbo.ElencoPersonale e INNER JOIN dbo.Profilo_militare p ON p.IDPersonale=e.IDPersonale INNER JOIN dbo.FFAA f ON f.ID_Arma=p.ID_Arma WHERE e.Stato_Servizio='attivo' AND e.Militare=1 GROUP BY f.SiglaArma ORDER BY f.SiglaArma"));Bind(Categorico,Leggi(@"SELECT CASE p.Categorico WHEN 'U' THEN 'Ufficiali' WHEN 'S' THEN 'Sottufficiali' WHEN 'T' THEN 'Truppa' ELSE ISNULL(p.Categorico,'Non indicato') END,COUNT(*) FROM dbo.ElencoPersonale e INNER JOIN dbo.Profilo_militare p ON p.IDPersonale=e.IDPersonale WHERE e.Stato_Servizio='attivo' AND e.Militare=1 GROUP BY p.Categorico ORDER BY p.Categorico"));Bind(ProfiloCivile,Leggi(@"SELECT RTRIM(t.Sigla_titolo),COUNT(*) FROM dbo.ElencoPersonale e INNER JOIN dbo.PersCivile p ON p.IDPersonale=e.IDPersonale INNER JOIN dbo.Titoli t ON t.ID_Titolo=p.ID_TitoloAtt WHERE e.Stato_Servizio='attivo' AND e.Militare=0 GROUP BY t.Sigla_titolo ORDER BY COUNT(*) DESC"));Bind(TitoloStudio,Leggi(@"SELECT ts.Desc_Tit_Studio,COUNT(*) FROM dbo.ElencoPersonale e INNER JOIN dbo.Titoli_Studio ts ON ts.id_Tit_Studio=e.id_Tit_Studio WHERE e.Stato_Servizio='attivo' GROUP BY ts.Desc_Tit_Studio ORDER BY COUNT(*) DESC"));}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 private IList<VoceReport> Leggi(string sql){var x=new List<VoceReport>();int totale=0;string cs=ConfigurationManager.ConnectionStrings["DipendentiDB"].ConnectionString;using(var c=new SqlConnection(cs))using(var q=new SqlCommand(sql,c)){c.Open();using(var r=q.ExecuteReader())while(r.Read()){int n=Convert.ToInt32(r.GetValue(1));totale+=n;x.Add(new VoceReport{Etichetta=r.IsDBNull(0)?"Non indicato":Convert.ToString(r.GetValue(0)).Trim(),Conteggio=n});}}foreach(var v in x)v.Percentuale=totale==0?0:Math.Round((decimal)v.Conteggio*100/totale,1);return x;}
 private static void Bind(System.Web.UI.WebControls.Repeater r,IList<VoceReport> x){r.DataSource=x;r.DataBind();}
</script>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Composizione del personale</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Indice.aspx">← Torna ai report</a><div class="page-heading report-title-actions"><div><p class="eyebrow">Forza effettiva</p><h1>Composizione del personale</h1><p>Conteggi e distribuzioni percentuali del personale in stato di servizio attivo.</p></div><button type="button" class="button secondary no-print" onclick="window.print()">Stampa report</button></div><asp:Label ID="Message" runat="server" CssClass="message error" Visible="false" />
 <div class="chart-report-grid">
  <section class="card chart-card"><h2>Militari e civili</h2><asp:Repeater ID="Tipo" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
  <section class="card chart-card"><h2>Uomini e donne</h2><asp:Repeater ID="Sesso" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
  <section class="card chart-card"><h2>Militari per forza armata</h2><asp:Repeater ID="ForzaArmata" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
  <section class="card chart-card"><h2>Militari per categorico</h2><asp:Repeater ID="Categorico" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
  <section class="card chart-card"><h2>Profili del personale civile</h2><asp:Repeater ID="ProfiloCivile" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
  <section class="card chart-card"><h2>Titoli di studio</h2><asp:Repeater ID="TitoloStudio" runat="server"><ItemTemplate><div class="metric-row"><div><strong><%# Eval("Etichetta") %></strong><span><%# Eval("Conteggio") %> · <%# Eval("PercentualeTesto") %></span></div><div class="metric-track"><span style='width:<%# Eval("Larghezza") %>'></span></div></div></ItemTemplate></asp:Repeater></section>
 </div>
</asp:Content>
