<%@ Page Title="Cruscotto FEO" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<%@ Import Namespace="System.Configuration" %><%@ Import Namespace="System.Data" %><%@ Import Namespace="System.Data.SqlClient" %><%@ Import Namespace="System.Globalization" %>
<script runat="server">
 private string Cs{get{return ConfigurationManager.ConnectionStrings["DipendentiDB"].ConnectionString;}}
 protected override void OnLoad(EventArgs e){base.OnLoad(e);if(!IsPostBack)Carica();}
 private void Carica(){try{var d=Dati();long m=S(d,"Militari"),c=S(d,"Civili"),t=m+c;Total.Text=t.ToString("N0");Military.Text=m.ToString("N0");Civil.Text=c.ToString("N0");MilitaryPct.Text=P(m,t);CivilPct.Text=P(c,t);Units.Text=d.Rows.Count.ToString();Average.Text=(d.Rows.Count==0?0:Math.Round(t*1m/d.Rows.Count,1)).ToString("N1");if(d.Rows.Count>0){LargestValue.Text=Convert.ToInt64(d.Rows[0]["Totale"]).ToString("N0");LargestName.Text=Server.HtmlEncode(Convert.ToString(d.Rows[0]["Unita"]));}Items.DataSource=d;Items.DataBind();Message.Visible=false;}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 private DataTable Dati(){var d=new DataTable();string sql=@"SELECT u.ID_Uff1,RTRIM(u.SgUff1)+' - '+ISNULL(u.DescUff1,'') Unita,COUNT(DISTINCT CASE WHEN ep.Militare=1 THEN ep.IDPersonale END) Militari,COUNT(DISTINCT CASE WHEN ep.Militare=0 THEN ep.IDPersonale END) Civili,COUNT(DISTINCT ep.IDPersonale) Totale FROM dbo.Liv1Uff u INNER JOIN dbo.Incarichi i ON i.ID_Uff1=u.ID_Uff1 AND i.principale=1 INNER JOIN dbo.ElencoPersonale ep ON ep.IDPersonale=i.IDPersonale WHERE ep.Stato_Servizio='attivo' AND u.ID_Uff1<>22 GROUP BY u.ID_Uff1,u.SgUff1,u.DescUff1 ORDER BY Totale DESC,u.SgUff1";using(var c=new SqlConnection(Cs))using(var q=new SqlCommand(sql,c)){c.Open();using(var a=new SqlDataAdapter(q))a.Fill(d);}d.Columns.Add("Incidenza",typeof(decimal));d.Columns.Add("QuotaM",typeof(decimal));d.Columns.Add("QuotaC",typeof(decimal));long all=S(d,"Totale");foreach(DataRow r in d.Rows){long x=Convert.ToInt64(r["Totale"]);r["Incidenza"]=all==0?0:Math.Round(x*100m/all,1);r["QuotaM"]=x==0?0:Math.Round(Convert.ToInt64(r["Militari"])*100m/x,1);r["QuotaC"]=x==0?0:Math.Round(Convert.ToInt64(r["Civili"])*100m/x,1);}return d;}
 private static long S(DataTable d,string n){long x=0;foreach(DataRow r in d.Rows)x+=Convert.ToInt64(r[n]);return x;}private static string P(long x,long t){return t==0?"0,0%":(x*100m/t).ToString("0.0")+"%";}protected string Percent(object x){return Convert.ToDecimal(x).ToString("0.0")+"%";}protected string Width(object x){return Convert.ToDecimal(x).ToString("0.0",CultureInfo.InvariantCulture)+"%";}
</script>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Cruscotto FEO</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Feo.aspx">← Report FEO</a><div class="page-heading"><p class="eyebrow">Forza effettiva organica</p><h1>Cruscotto direzionale FEO</h1><p>Quadro sintetico della consistenza e della distribuzione del personale attivo tra i reparti.</p></div>
 <nav class="section-nav"><a href="#lettura">Guida alla lettura</a><a href="#indicatori">Indicatori</a><a href="#reparti">Reparti</a><a href="FeoDistribuzione.aspx?livello=1">Esplora struttura</a><a href="TtooConsistenza.aspx">Analisi organico</a></nav><asp:Label ID="Message" runat="server" CssClass="message error" Visible="false"/>
 <section id="lettura" class="card detail-section anchor-section"><h2>Cosa rappresenta</h2><p>Il cruscotto aggrega per reparto il personale attivo associato all’incarico principale. Gli indicatori riassumono consistenza totale, composizione militare e civile, numero dei reparti, consistenza media e reparto con più personale.</p><h3>Cosa è possibile analizzare</h3><p>La graduatoria permette di confrontare dimensione, incidenza sul totale e composizione interna dei reparti. Dal collegamento “Divisioni” si prosegue nell’analisi gerarchica della struttura.</p></section>
 <section id="indicatori" class="feo-dashboard-kpis anchor-section"><div class="card"><span>Personale presente</span><strong><asp:Literal ID="Total" runat="server"/></strong></div><div class="card"><span>Militari</span><strong><asp:Literal ID="Military" runat="server"/></strong><small><asp:Literal ID="MilitaryPct" runat="server"/></small></div><div class="card"><span>Civili</span><strong><asp:Literal ID="Civil" runat="server"/></strong><small><asp:Literal ID="CivilPct" runat="server"/></small></div><div class="card"><span>Reparti rilevati</span><strong><asp:Literal ID="Units" runat="server"/></strong></div><div class="card"><span>Media per reparto</span><strong><asp:Literal ID="Average" runat="server"/></strong></div><div class="card"><span>Reparto maggiore</span><strong><asp:Literal ID="LargestValue" runat="server"/></strong><small><asp:Literal ID="LargestName" runat="server"/></small></div></section>
 <section id="reparti" class="card report-wide anchor-section"><h2>Distribuzione per reparto</h2><p class="field-hint">Ordinamento per consistenza decrescente.</p><asp:GridView ID="Items" runat="server" AutoGenerateColumns="false" CssClass="data-grid" EmptyDataText="Nessun dato disponibile."><Columns><asp:TemplateField HeaderText="#"><ItemTemplate><%# Container.DataItemIndex+1 %></ItemTemplate></asp:TemplateField><asp:BoundField DataField="Unita" HeaderText="Reparto"/><asp:BoundField DataField="Militari" HeaderText="Militari"/><asp:BoundField DataField="Civili" HeaderText="Civili"/><asp:BoundField DataField="Totale" HeaderText="Totale"/><asp:TemplateField HeaderText="Incidenza"><ItemTemplate><div class="feo-bar"><span style='<%# "width:"+Width(Eval("Incidenza")) %>'></span></div><small><%# Percent(Eval("Incidenza")) %></small></ItemTemplate></asp:TemplateField><asp:TemplateField HeaderText="Composizione M/C"><ItemTemplate><div class="feo-composition"><span class="military" style='<%# "width:"+Width(Eval("QuotaM")) %>'></span><span class="civilian" style='<%# "width:"+Width(Eval("QuotaC")) %>'></span></div><small>M <%# Percent(Eval("QuotaM")) %> · C <%# Percent(Eval("QuotaC")) %></small></ItemTemplate></asp:TemplateField><asp:TemplateField><ItemTemplate><a href='<%# "FeoDistribuzione.aspx?livello=2&u1="+Eval("ID_Uff1") %>'>Divisioni</a></ItemTemplate></asp:TemplateField></Columns></asp:GridView></section>
</asp:Content>
