<%@ Page Title="Distribuzione FEO" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<%@ Import Namespace="System.Configuration" %><%@ Import Namespace="System.Data" %><%@ Import Namespace="System.Data.SqlClient" %><%@ Import Namespace="System.Globalization" %><%@ Import Namespace="System.Text" %>
<script runat="server">
 private string Cs{get{return ConfigurationManager.ConnectionStrings["DipendentiDB"].ConnectionString;}} protected int Livello{get{int n;return int.TryParse(Request.QueryString["livello"],out n)&&n>=1&&n<=3?n:1;}} private int? Q(string n){int x;return int.TryParse(Request.QueryString[n],out x)&&x>0?(int?)x:null;}
 protected override void OnLoad(EventArgs e){base.OnLoad(e);if(!IsPostBack){Tipo.SelectedValue=NormalizzaTipo(Request.QueryString["tipo"]);Carica();}}
 protected void Tipo_Changed(object s,EventArgs e){Response.Redirect(UrlCorrente(),false);Context.ApplicationInstance.CompleteRequest();} protected void Export_Click(object s,EventArgs e){Esporta(Dati());}
 private void Carica(){try{if(Livello>=2&&!Q("u1").HasValue)throw new InvalidOperationException("Per consultare il secondo livello selezionare un reparto.");if(Livello==3&&!Q("u2").HasValue)throw new InvalidOperationException("Per consultare il terzo livello selezionare una divisione.");DataTable d=Dati();AggiungiCalcoli(d);Items.DataSource=d;Items.DataBind();long m=Somma(d,"Militari"),c=Somma(d,"Civili");KpiTotal.Text=(m+c).ToString("N0");KpiMilitary.Text=m.ToString("N0");KpiCivil.Text=c.ToString("N0");Count.Text=d.Rows.Count+" unità";TitleView.Text=Server.HtmlEncode(Contesto());Message.Visible=false;}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 private DataTable Dati(){int l=Livello;string unit=l==1?"dbo.Liv1Uff u":"dbo.Liv2Uff u";if(l==3)unit="dbo.Liv3Uff u";string id=l==1?"u.ID_Uff1":l==2?"u.ID_Uff2":"u.ID_Uff3";string sig=l==1?"u.SgUff1":l==2?"u.SgUff2":"u.SgUff3";string des=l==1?"u.DescUff1":l==2?"u.DescUff2":"u.DescUff3";string join=l==1?"u.ID_Uff1=i.ID_Uff1":l==2?"u.ID_Uff1=i.ID_Uff1 AND u.ID_Uff2=i.ID_Uff2":"u.ID_Uff1=i.ID_Uff1 AND u.ID_Uff2=i.ID_Uff2 AND u.ID_Uff3=i.ID_Uff3";string where=l==1?"u.ID_Uff1<>@empty":l==2?"u.ID_Uff1=@u1 AND u.ID_Uff2<>@empty":"u.ID_Uff1=@u1 AND u.ID_Uff2=@u2 AND u.ID_Uff3<>@empty";string sql="SELECT "+id+" ID_UO,u.ID_Uff1"+(l==1?"":",u.ID_Uff2")+",RTRIM("+sig+")+' - '+ISNULL("+des+",'') Unita,COUNT(DISTINCT CASE WHEN ep.Militare=1 THEN ep.IDPersonale END) Militari,COUNT(DISTINCT CASE WHEN ep.Militare=0 THEN ep.IDPersonale END) Civili,COUNT(DISTINCT ep.IDPersonale) Totale FROM "+unit+" INNER JOIN dbo.Incarichi i ON "+join+" AND i.principale=1 INNER JOIN dbo.ElencoPersonale ep ON ep.IDPersonale=i.IDPersonale WHERE ep.Stato_Servizio='attivo' AND "+where+" AND (@tipo='' OR (@tipo='M' AND ep.Militare=1) OR (@tipo='C' AND ep.Militare=0)) GROUP BY "+id+",u.ID_Uff1"+(l==1?"":",u.ID_Uff2")+","+sig+","+des+" ORDER BY Totale DESC,"+sig;var d=new DataTable();using(var c=new SqlConnection(Cs))using(var q=new SqlCommand(sql,c)){q.Parameters.Add("@empty",SqlDbType.Int).Value=l==1?22:l==2?119:195;q.Parameters.Add("@tipo",SqlDbType.Char,1).Value=Tipo.SelectedValue;if(l>=2)q.Parameters.Add("@u1",SqlDbType.Int).Value=Q("u1").Value;if(l==3)q.Parameters.Add("@u2",SqlDbType.Int).Value=Q("u2").Value;c.Open();using(var a=new SqlDataAdapter(q))a.Fill(d);}return d;}
 private void AggiungiCalcoli(DataTable d){d.Columns.Add("Incidenza",typeof(decimal));d.Columns.Add("QuotaM",typeof(decimal));d.Columns.Add("QuotaC",typeof(decimal));d.Columns.Add("NextUrl",typeof(string));long all=Somma(d,"Totale");foreach(DataRow r in d.Rows){long t=Convert.ToInt64(r["Totale"]);r["Incidenza"]=all==0?0:Math.Round(t*100m/all,1);r["QuotaM"]=t==0?0:Math.Round(Convert.ToInt64(r["Militari"])*100m/t,1);r["QuotaC"]=t==0?0:Math.Round(Convert.ToInt64(r["Civili"])*100m/t,1);if(Livello==1)r["NextUrl"]="FeoDistribuzione.aspx?livello=2&u1="+r["ID_UO"]+TipoParametro();else if(Livello==2)r["NextUrl"]="FeoDistribuzione.aspx?livello=3&u1="+r["ID_Uff1"]+"&u2="+r["ID_UO"]+TipoParametro();else r["NextUrl"]="";}}
 private string Contesto(){if(Livello==1)return "Personale per reparto";return (Livello==2?"Divisioni di ":"Sezioni di ")+NomePadre();} private string NomePadre(){string table=Livello==2?"Liv1Uff":"Liv2Uff",id=Livello==2?"ID_Uff1":"ID_Uff2",sig=Livello==2?"SgUff1":"SgUff2",des=Livello==2?"DescUff1":"DescUff2";using(var c=new SqlConnection(Cs))using(var q=new SqlCommand("SELECT RTRIM("+sig+")+' - '+ISNULL("+des+",'') FROM dbo."+table+" WHERE "+id+"=@id",c)){q.Parameters.Add("@id",SqlDbType.Int).Value=Livello==2?Q("u1").Value:Q("u2").Value;c.Open();return Convert.ToString(q.ExecuteScalar());}}
 private string UrlCorrente(){return "FeoDistribuzione.aspx?livello="+Livello+(Q("u1").HasValue?"&u1="+Q("u1").Value:"")+(Q("u2").HasValue?"&u2="+Q("u2").Value:"")+TipoParametro();}private string TipoParametro(){return string.IsNullOrEmpty(Tipo.SelectedValue)?"":"&tipo="+Tipo.SelectedValue;}private static string NormalizzaTipo(string x){return x=="M"||x=="C"?x:"";}protected bool HaDettaglio(object x){return !string.IsNullOrEmpty(Convert.ToString(x));}protected string P(object x){return Convert.ToDecimal(x).ToString("0.0")+"%";}protected string W(object x){return Convert.ToDecimal(x).ToString("0.0",CultureInfo.InvariantCulture)+"%";}private static long Somma(DataTable d,string n){long x=0;foreach(DataRow r in d.Rows)x+=Convert.ToInt64(r[n]);return x;}
 private void Esporta(DataTable d){AggiungiCalcoli(d);var b=new StringBuilder("Unità;Militari;Civili;Totale;Incidenza\r\n");foreach(DataRow r in d.Rows)b.Append(Csv(Convert.ToString(r["Unita"]))).Append(';').Append(r["Militari"]).Append(';').Append(r["Civili"]).Append(';').Append(r["Totale"]).Append(';').Append(r["Incidenza"]).AppendLine();Response.Clear();Response.ContentType="text/csv";Response.ContentEncoding=Encoding.UTF8;Response.AddHeader("Content-Disposition","attachment; filename=FEO_distribuzione_livello_"+Livello+".csv");Response.BinaryWrite(Encoding.UTF8.GetPreamble());Response.Write(b.ToString());Response.End();}private static string Csv(string x){return "\""+(x??"").Replace("\"","\"\"")+"\"";}
</script>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Distribuzione FEO</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Feo.aspx">← Report FEO</a><div class="page-heading"><p class="eyebrow">Forza effettiva organica</p><h1><asp:Literal ID="TitleView" runat="server" /></h1><p>Distribuzione del personale attivo in base all’unità dell’incarico principale.</p></div>
 <nav class="section-nav"><a href="#lettura">Guida alla lettura</a><a href="#riepilogo">Riepilogo</a><a href="#risultati">Risultati</a><a href="FeoDistribuzione.aspx?livello=1">Reparti</a><a href="FeoCruscotto.aspx">Cruscotto</a><a href="TtooConsistenza.aspx">Analisi organico</a></nav><asp:Label ID="Message" runat="server" CssClass="message error" Visible="false"/>
 <section id="lettura" class="card detail-section anchor-section"><h2>Cosa rappresenta</h2><p>Ogni riga è un’unità organizzativa e riporta le persone attive che vi risultano assegnate con incarico principale. L’incidenza misura il peso dell’unità sul totale visualizzato; la composizione M/C evidenzia il rapporto interno tra militari e civili.</p><h3>Cosa è possibile analizzare</h3><p>Si può confrontare la dimensione delle unità, filtrare militari o civili e approfondire la struttura dal reparto alla divisione e quindi alla sezione.</p></section>
 <section id="riepilogo" class="card report-filters anchor-section"><div><label>Tipo personale</label><asp:DropDownList ID="Tipo" runat="server" AutoPostBack="true" OnSelectedIndexChanged="Tipo_Changed"><asp:ListItem Value="">Tutto il personale</asp:ListItem><asp:ListItem Value="M">Solo militari</asp:ListItem><asp:ListItem Value="C">Solo civili</asp:ListItem></asp:DropDownList></div></section>
 <section class="ttoo-kpi-grid"><div class="card"><span>Totale</span><strong><asp:Literal ID="KpiTotal" runat="server"/></strong></div><div class="card"><span>Militari</span><strong><asp:Literal ID="KpiMilitary" runat="server"/></strong></div><div class="card"><span>Civili</span><strong><asp:Literal ID="KpiCivil" runat="server"/></strong></div></section>
 <section id="risultati" class="card report-wide anchor-section"><div class="report-section-title"><asp:Label ID="Count" runat="server" CssClass="result-count"/><asp:Button runat="server" Text="Esporta CSV" CssClass="button secondary" OnClick="Export_Click"/></div><asp:GridView ID="Items" runat="server" AutoGenerateColumns="false" CssClass="data-grid" EmptyDataText="Nessun dato disponibile."><Columns><asp:BoundField DataField="Unita" HeaderText="Unità organizzativa"/><asp:BoundField DataField="Militari" HeaderText="Militari"/><asp:BoundField DataField="Civili" HeaderText="Civili"/><asp:BoundField DataField="Totale" HeaderText="Totale"/><asp:TemplateField HeaderText="Incidenza"><ItemTemplate><div class="feo-bar"><span style='<%# "width:"+W(Eval("Incidenza")) %>'></span></div><small><%# P(Eval("Incidenza")) %></small></ItemTemplate></asp:TemplateField><asp:TemplateField HeaderText="Composizione M/C"><ItemTemplate><div class="feo-composition"><span class="military" style='<%# "width:"+W(Eval("QuotaM")) %>'></span><span class="civilian" style='<%# "width:"+W(Eval("QuotaC")) %>'></span></div><small>M <%# P(Eval("QuotaM")) %> · C <%# P(Eval("QuotaC")) %></small></ItemTemplate></asp:TemplateField><asp:TemplateField><ItemTemplate><asp:HyperLink runat="server" Text="Dettaglio" NavigateUrl='<%# Eval("NextUrl") %>' Visible='<%# HaDettaglio(Eval("NextUrl")) %>'/></ItemTemplate></asp:TemplateField></Columns></asp:GridView></section>
</asp:Content>
