<%@ Page Title="Report" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Report</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="../Default.aspx">← Torna alla pagina principale</a>
 <div class="page-heading"><p class="eyebrow">Reportistica</p><h1>Catalogo dei report</h1><p>Le famiglie di report previste riprendono funzionalità, filtri ed esportazioni disponibili in WebGestPers legacy.</p></div>
 <nav class="section-nav" aria-label="Famiglie di report"><a href="#inout">IN/OUT</a><a href="#chart">Chart</a><a href="#ttoo">TTOO</a><a href="#feo">FEO</a></nav>
 <div class="report-catalog">
  <section id="inout" class="card report-family anchor-section"><div class="report-family-header"><div><p class="eyebrow">IN/OUT</p><h2>Personale in entrata e uscita</h2><p>Movimenti registrati tramite data di assegnazione e data di uscita.</p></div><span class="report-status report-ready">Disponibile</span></div><h3>Funzioni</h3><ul><li>Personale entrato negli ultimi 3, 6, 12, 24 o 36 mesi.</li><li>Personale uscito negli stessi intervalli.</li><li>Esportazione CSV separata per ingressi e uscite, apribile con Excel.</li></ul><a class="button reports-button" href="InOut.aspx">Apri report IN/OUT</a></section>
  <section id="chart" class="card report-family anchor-section"><div class="report-family-header"><div><p class="eyebrow">CHART</p><h2>Composizione del personale</h2><p>Prospetti numerici e rappresentazioni grafiche della forza effettiva.</p></div><span class="report-status report-ready">Disponibile</span></div><h3>Funzioni</h3><ul><li>Personale militare e civile.</li><li>Distribuzione uomini e donne.</li><li>Militari per forza armata e categorico.</li><li>Titoli di studio e profili del personale civile.</li><li>Versione ottimizzata per la stampa.</li></ul><a class="button reports-button" href="Chart.aspx">Apri composizione personale</a></section>
  <section id="ttoo" class="card report-family anchor-section"><div class="report-family-header"><div><p class="eyebrow">TTOO</p><h2>Tabelle organiche</h2><p>Gestione delle posizioni previste e confronto con la forza effettiva organica.</p></div><span class="report-status report-ready">Disponibile</span></div><h3>Funzioni</h3><ul><li>Inserimento, modifica e disattivazione delle posizioni TTOO.</li><li>Associazione a uffici di 1°, 2° e 3° livello.</li><li>Profili previsti distinti tra personale militare e civile.</li><li>Confronto TTOO/FEO con scoperture, eccedenze ed esportazione CSV.</li></ul><a class="button reports-button" href="Ttoo.aspx">Apri gestione TTOO</a></section>
  <section id="feo" class="card report-family anchor-section"><div class="report-family-header"><div><p class="eyebrow">FEO</p><h2>Forza effettiva organica</h2><p>Personale attivo associato alle unità organizzative tramite l’incarico principale.</p></div><span class="report-status report-ready">Disponibile</span></div><h3>Funzioni</h3><ul><li>Cruscotto direzionale con indicatori e graduatoria dei reparti.</li><li>Distribuzione di militari e civili fino al terzo livello.</li><li>Incidenza delle unità e composizione interna militari/civili.</li><li>Confronto con le TTOO ed esportazione CSV.</li></ul><a class="button reports-button" href="Feo.aspx">Apri report FEO</a></section>
 </div>
</asp:Content>
