using System;using System.Collections.Generic;using System.Data;using System.Data.SqlClient;using WebGestPersV2.Data;using WebGestPersV2.Models;
namespace WebGestPersV2.PersonaleEsterno { public partial class Modifica:Security.BaseAuthenticatedPage { protected override int[] LivelliConsentiti{get{return new[]{150,160,170,200};}} private int Id{get{int x;return int.TryParse(Request.QueryString["id"],out x)?x:0;}} private PersonaleEsternoRepository Repository{get{return new PersonaleEsternoRepository();}}
 protected void Page_Load(object s,EventArgs e){if(Id<=0){Response.Redirect("Elenco.aspx",true);return;}if(!IsPostBack)Carica();}
 private void Carica(){var p=Repository.Trova(Id);if(p==null){Response.Redirect("Elenco.aspx",true);return;}Heading.Text=Server.HtmlEncode(p.Cognome+" "+p.Nome);Nuovo.Bind(Company,Repository.Ditte(),"-- seleziona --");Nuovo.Bind(Office1,Repository.Uffici1(),"-- ufficio predefinito --");Seleziona(Company,p.IdDitta);Seleziona(Office1,p.IdUfficio1);CaricaUffici2(p.IdUfficio2);CaricaUffici3(p.IdUfficio3);LastName.Text=p.Cognome;FirstName.Text=p.Nome;TaxCode.Text=p.CodiceFiscale;Phone.Text=p.Telefono;Room.Text=p.Stanza;Active.Checked=p.Attivo;DeactivateButton.Visible=p.Attivo;CaricaStorico();}
 protected void Office1_Changed(object s,EventArgs e){CaricaUffici2(null);Nuovo.Bind(Office3,new List<LookupItem>(),"-- ufficio predefinito --");}
 protected void Office2_Changed(object s,EventArgs e){CaricaUffici3(null);}
 private void CaricaUffici2(int? selezione){int id;Nuovo.Bind(Office2,int.TryParse(Office1.SelectedValue,out id)?Repository.Uffici2(id):new List<LookupItem>(),"-- ufficio predefinito --");Seleziona(Office2,selezione);}
 private void CaricaUffici3(int? selezione){int id;Nuovo.Bind(Office3,int.TryParse(Office2.SelectedValue,out id)?Repository.Uffici3(id):new List<LookupItem>(),"-- ufficio predefinito --");Seleziona(Office3,selezione);}
 protected void SaveButton_Click(object s,EventArgs e){Page.Validate("external");if(!Page.IsValid)return;try{Repository.Aggiorna(Leggi(),Context.User.Identity.Name);Response.Redirect("Modifica.aspx?id="+Id,false);Context.ApplicationInstance.CompleteRequest();}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 protected void DeactivateButton_Click(object s,EventArgs e){try{Repository.Disattiva(Id,Context.User.Identity.Name);Response.Redirect("Elenco.aspx",false);Context.ApplicationInstance.CompleteRequest();}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 private PersonaleEsternoRequest Leggi(){int d,u1,u2,u3;return new PersonaleEsternoRequest{Id=Id,Cognome=LastName.Text.Trim(),Nome=FirstName.Text.Trim(),CodiceFiscale=TaxCode.Text.Trim().ToUpperInvariant(),Telefono=Phone.Text.Trim(),Stanza=Room.Text.Trim(),IdDitta=int.TryParse(Company.SelectedValue,out d)?d:0,IdUfficio1=int.TryParse(Office1.SelectedValue,out u1)?(int?)u1:null,IdUfficio2=int.TryParse(Office2.SelectedValue,out u2)?(int?)u2:null,IdUfficio3=int.TryParse(Office3.SelectedValue,out u3)?(int?)u3:null,Attivo=Active.Checked};}
 private void CaricaStorico(){const string sql="SELECT Campo_Variato AS Campo,Data_Modifica AS Data,Utente_Modificatore AS Utente,Valore_Vecchio AS Prima,Valore_Nuovo AS Dopo FROM dbo.PE_StoricoModifiche WHERE ID_Pe=@Id ORDER BY Data_Modifica DESC,ID_Storico DESC";var table=new DataTable();using(var c=new SqlConnection(Db.ConnectionString))using(var q=new SqlCommand(sql,c)){q.Parameters.Add("@Id",SqlDbType.Int).Value=Id;using(var a=new SqlDataAdapter(q))a.Fill(table);}HistoryGrid.DataSource=table;HistoryGrid.DataBind();}
 private static void Seleziona(System.Web.UI.WebControls.DropDownList c,int? id){if(id.HasValue&&c.Items.FindByValue(id.Value.ToString())!=null)c.SelectedValue=id.Value.ToString();}
 } }
