using System;using System.Collections.Generic;using System.Web.UI.WebControls;using WebGestPersV2.Data;using WebGestPersV2.Models;
namespace WebGestPersV2.PersonaleEsterno { public partial class Nuovo:Security.BaseAuthenticatedPage { protected override int[] LivelliConsentiti{get{return new[]{150,160,170,200};}} private PersonaleEsternoRepository Repository{get{return new PersonaleEsternoRepository();}}
 protected void Page_Load(object s,EventArgs e){if(!IsPostBack){Bind(Company,Repository.Ditte(),"-- seleziona --");Bind(Office1,Repository.Uffici1(),"-- ufficio predefinito --");Bind(Office2,new List<LookupItem>(),"-- ufficio predefinito --");Bind(Office3,new List<LookupItem>(),"-- ufficio predefinito --");}}
 protected void Office1_Changed(object s,EventArgs e){int id;Bind(Office2,int.TryParse(Office1.SelectedValue,out id)?Repository.Uffici2(id):new List<LookupItem>(),"-- ufficio predefinito --");Bind(Office3,new List<LookupItem>(),"-- ufficio predefinito --");}
 protected void Office2_Changed(object s,EventArgs e){int id;Bind(Office3,int.TryParse(Office2.SelectedValue,out id)?Repository.Uffici3(id):new List<LookupItem>(),"-- ufficio predefinito --");}
 protected void SaveButton_Click(object s,EventArgs e){Page.Validate("external");if(!Page.IsValid)return;try{var d=Leggi();int id=Repository.Inserisci(d,Context.User.Identity.Name);Response.Redirect("Modifica.aspx?id="+id,false);Context.ApplicationInstance.CompleteRequest();}catch(Exception ex){Message.Text=Server.HtmlEncode(ex.Message);Message.Visible=true;}}
 private PersonaleEsternoRequest Leggi(){int d,u1,u2,u3;return new PersonaleEsternoRequest{Cognome=LastName.Text.Trim(),Nome=FirstName.Text.Trim(),CodiceFiscale=TaxCode.Text.Trim().ToUpperInvariant(),Telefono=Phone.Text.Trim(),Stanza=Room.Text.Trim(),IdDitta=int.TryParse(Company.SelectedValue,out d)?d:0,IdUfficio1=int.TryParse(Office1.SelectedValue,out u1)?(int?)u1:null,IdUfficio2=int.TryParse(Office2.SelectedValue,out u2)?(int?)u2:null,IdUfficio3=int.TryParse(Office3.SelectedValue,out u3)?(int?)u3:null,Attivo=true};}
 internal static void Bind(DropDownList c,IList<LookupItem> d,string p){c.Items.Clear();c.Items.Add(new ListItem(p,""));foreach(var x in d)c.Items.Add(new ListItem(x.Text,x.Value));}
 } }
