<%@ Page Title="Guida tecnica" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Guida tecnica</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Default.aspx">← Torna all’Help</a>
 <div class="page-heading"><p class="eyebrow">Amministrazione e sviluppo</p><h1>Guida tecnica di WebGestPers v2</h1><p>Riferimento generale per gestione operativa, configurazione e manutenzione dell’applicazione.</p></div>
 <nav class="section-nav" aria-label="Argomenti della guida"><a href="#architettura">Architettura</a><a href="#permessi">Permessi</a><a href="#personale">Personale</a><a href="#incarichi">Incarichi</a><a href="#tabelle">Tabelle</a><a href="#report">Report</a><a href="#audit">Audit e log</a><a href="#configurazione">Configurazione</a><a href="#database">Database</a><a href="#rilascio">Rilascio</a></nav>
 <div class="guide-content">
  <section id="architettura" class="card detail-section anchor-section"><h2>Architettura</h2><p>WebGestPers v2 è un’applicazione ASP.NET Web Forms in C#, destinata a .NET Framework 4.6 e Visual Studio 2019. Le pagine <code>.aspx</code> gestiscono l’interfaccia, i code-behind coordinano i flussi e i repository nella cartella <code>Data</code> accedono a SQL Server tramite ADO.NET.</p><p>I modelli sono nella cartella <code>Models</code>; la configurazione applicativa è esposta dalla classe <code>Configuration.AppConfig</code>.</p></section>
  <section id="permessi" class="card detail-section anchor-section"><h2>Autenticazione e autorizzazioni</h2><p>L’applicazione usa Windows Authentication. <code>BaseAuthenticatedPage</code> cerca l’identità corrente nella tabella <code>Autorizzazioni</code> e verifica i livelli ammessi dalla pagina.</p><ul><li>Livello 150: amministrazione del personale militare.</li><li>Livello 160: amministrazione del personale civile.</li><li>Livello 170: amministrazione civile e militare.</li><li>Livello 200: amministrazione completa.</li></ul><p>Ogni nuova funzione di scrittura deve ripetere il controllo sul tipo di personale anche lato server.</p></section>
  <section id="personale" class="card detail-section anchor-section"><h2>Gestione del personale</h2><p>Inserimento e modifica distinguono profilo civile e militare. Per i militari sono gestiti anche forza armata, grado, ruolo, categoria e specialità; per i civili profilo professionale, posizione economica e dati collegati.</p><p>Il passaggio dallo stato attivo a un altro stato valorizza la data di uscita e chiude tutti gli incarichi aperti. Le variazioni dei dati del dipendente vengono registrate in <code>StoricoModifiche</code> e sono consultabili dalla pagina di dettaglio.</p></section>
  <section id="incarichi" class="card detail-section anchor-section"><h2>Gestione degli incarichi</h2><p>Gli incarichi possono essere inseriti, modificati o chiusi anche senza cambiare lo stato di servizio. La chiusura copia i dati in <code>StoricoIncarichi</code>, valorizza la data finale e rimuove l’incarico corrente.</p><p>Se una persona ancora attiva rimane senza incarichi, il sistema assegna quello predefinito utilizzando gli identificativi presenti nella configurazione. Le operazioni correlate devono restare racchiuse nella medesima transazione.</p></section>
  <section id="tabelle" class="card detail-section anchor-section"><h2>Tabelle di gestione</h2><p>Le tabelle comuni comprendono titoli di studio, fasce orarie, toponomastica, tipi di incarico e uffici dei tre livelli. Le tabelle civili comprendono qualifiche, posizioni economiche e ASL; quelle militari comprendono gradi, ruoli, categorie e specialità per forza armata.</p><p>Prima di eliminare o modificare una voce verificare sempre eventuali riferimenti nei profili e negli incarichi.</p></section>
  <section id="report" class="card detail-section anchor-section"><h2>Report, TTOO e FEO</h2><p>I report IN/OUT producono elenchi temporali ed esportazioni Excel. Le TTOO rappresentano le posizioni teoricamente previste, articolate fino al terzo livello, e supportano inserimento, modifica ed eliminazione. La consistenza confronta tali posizioni con gli incarichi principali del personale attivo.</p><p>La FEO descrive invece la forza effettiva presente e ne consente l’analisi per struttura. Quando si modificano query o filtri, mantenere distinta la posizione teorica TTOO dal personale effettivamente assegnato.</p></section>
  <section id="audit" class="card detail-section anchor-section"><h2>Audit applicativo e log</h2><p>Le operazioni CRUD principali sono registrate tramite <code>Infrastructure.CrudLogger</code>. Ogni evento deve riportare almeno operazione, entità interessata, identificativo e identità Windows dell’operatore; gli errori devono includere l’eccezione.</p><p>Creazione e modifica del personale alimentano inoltre <code>StoricoModifiche</code> con campo variato, valore precedente, valore nuovo, data e utente. Questo storico è funzionale all’audit e non sostituisce il log tecnico su file.</p><p>I file sono prodotti giornalmente nel percorso configurato; se questo non è disponibile, viene utilizzata la cartella applicativa <code>App_Data\Logs</code>. L’account del pool IIS deve avere i permessi di scrittura.</p></section>
  <section id="configurazione" class="card detail-section anchor-section"><h2>Configurazione e risorse grafiche</h2><p>Le connection string e le impostazioni applicative risiedono in <code>Web.config</code>. Tra i valori principali figurano percorso delle foto, percorsi dei file, identificativi degli uffici predefiniti, mappature militari e percorso dei log.</p><p>Il codice applicativo deve leggere questi valori tramite <code>AppConfig</code>. Non inserire credenziali o percorsi specifici dell’ambiente nel codice sorgente. Le foto utilizzano il nome presente in <code>ElencoPersonale.ImgPath</code> e la radice configurata nell’applicazione.</p><p>Il logo visualizzato nell’intestazione comune è <code>img\nuovo_logo_armaereo.png</code> ed è richiamato da <code>Site.Master</code>. La cartella <code>img</code> deve essere inclusa nel progetto e copiata integralmente durante la pubblicazione.</p></section>
  <section id="database" class="card detail-section anchor-section"><h2>Database e transazioni</h2><p>Le scritture correlate devono essere eseguite nella stessa transazione SQL. Le modifiche significative vengono registrate in <code>StoricoModifiche</code>, indicando persona, campo variato, valori precedente e nuovo, data e identità Windows dell’operatore.</p><p>Prima di modificare query o mapping confrontare nomi, tipi e nullabilità con lo script di creazione del database.</p></section>
  <section id="rilascio" class="card detail-section anchor-section"><h2>Compilazione e rilascio</h2><p>Aprire la soluzione con Visual Studio 2019, verificare il target .NET Framework 4.6 e compilare prima in configurazione Debug. Il sito richiede IIS/IIS Express con Windows Authentication abilitata e autenticazione anonima disabilitata.</p><p>Durante la copia assicurarsi che siano inclusi anche i nuovi file e le cartelle di contenuto, compresa <code>img</code>, e che risultino presenti nel progetto. Prima del rilascio verificare connessione al database, autorizzazioni, logo e foto, log, storico modifiche, inserimento e modifica dei due tipi di personale, incarichi, tabelle amministrative, organigramma ed esportazioni Excel e report TTOO/FEO.</p></section>
 </div>
</asp:Content>
