<%@ Page Title="Guida utente" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Guida utente</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Default.aspx">← Torna all’Help</a>
 <div class="page-heading"><p class="eyebrow">Guida per l’utilizzatore</p><h1>Utilizzare WebGestPers</h1><p>Indicazioni essenziali per consultare correttamente le informazioni sul personale.</p></div>
 <nav class="section-nav" aria-label="Argomenti della guida"><a href="#accesso">Accesso</a><a href="#ricerca">Elenco e filtri</a><a href="#non-attivi">Personale non attivo</a><a href="#personale-esterno">Personale esterno</a><a href="#organigramma">Unità organizzative</a><a href="#profilo">Profilo</a><a href="#caselle-posta">Caselle di posta</a><a href="#incarichi">Incarichi</a><a href="#report">Report</a><a href="#esportazioni">Esportazioni</a><a href="#sicurezza">Sicurezza</a></nav>
 <div class="guide-content">
  <section id="accesso" class="card detail-section anchor-section"><h2>Accesso all’applicazione</h2><p>L’accesso utilizza l’identità Windows. Le funzioni disponibili dipendono dal livello associato all’utente nella tabella delle autorizzazioni. Se non si dispone del livello necessario viene mostrata la pagina di accesso negato.</p></section>
  <section id="ricerca" class="card detail-section anchor-section"><h2>Elenco, ricerca e filtri</h2><p>Dalla pagina principale selezionare <strong>Apri elenco personale</strong>. L’elenco iniziale comprende il personale con stato di servizio attivo. La ricerca libera consente di individuare una persona per cognome, nome o codice fiscale.</p><p>I filtri permettono di restringere l’elenco per tipo di personale, grado o profilo, forza armata, categorico e altri criteri disponibili. I filtri possono essere combinati; azzerarli per tornare all’elenco completo del personale attivo.</p><p>La colonna <strong>Grado/Profilo</strong> mostra il grado per il personale militare e la sigla del profilo professionale per il personale civile.</p></section>
  <section id="non-attivi" class="card detail-section anchor-section"><h2>Personale non attivo</h2><p>Gli amministratori autorizzati possono aprire dalla home l’elenco separato del personale con stato di servizio diverso da attivo. La pagina consente la ricerca per nominativo o codice fiscale e il filtro per stato.</p><p>Nel passaggio da attivo a un altro stato, gli incarichi effettivi vengono chiusi alla data indicata e trasferiti nello storico; l’eventuale <strong>Non assegnato</strong> viene soltanto rimosso. Da <strong>Modifica / Riattiva</strong> è possibile riportare la persona allo stato attivo: il sistema cancella la data di uscita, chiude e storicizza eventuali incarichi effettivi residui, elimina i segnaposto presenti e crea un unico <strong>Non assegnato</strong>, principale, sugli uffici configurati. Viene inoltre aggiunta una nota di riattivazione conservando le note precedenti.</p></section>
  <section id="organigramma" class="card detail-section anchor-section"><h2>Personale per unità organizzativa</h2><p>Dalla home selezionare <strong>Personale per unità</strong> per esplorare gli uffici fino al terzo livello. La visualizzazione comprende il personale attivo collocato secondo l’incarico principale; il numero accanto a ogni ufficio indica la consistenza dell’intero ramo.</p><p>È possibile espandere o comprimere le unità, cercare una persona, un incarico o un ufficio e filtrare tra personale militare e civile. Selezionando il nominativo si apre il relativo profilo. Il pulsante <strong>Esporta in Excel</strong> scarica i dati correntemente filtrati, completi dei tre livelli organizzativi.</p></section>
  <section id="profilo" class="card detail-section anchor-section"><h2>Consultare un profilo</h2><p>Selezionare una persona dall’elenco per aprirne il dettaglio. I pulsanti nella parte superiore consentono di raggiungere rapidamente dati generali, dati sensibili, profilo, incarichi, storico incarichi, storico modifiche e note.</p><p>Il profilo militare contiene grado, forza armata, posizione, categoria, ruolo e specialità. Il profilo civile contiene le informazioni di assunzione e il profilo professionale attuale.</p><p>Lo <strong>Storico modifiche</strong> mostra data e ora, campo variato, valori precedente e nuovo e utente che ha effettuato l’operazione.</p></section>
  <section id="caselle-posta" class="card detail-section anchor-section"><h2>Caselle di posta</h2><p>Nel profilo sono elencati gli indirizzi e-mail associati alla persona e la relativa tipologia: personale, funzionale, funzionale secondaria o condivisa. Gli amministratori autorizzati possono utilizzare <strong>Gestisci caselle di posta</strong> per aggiungere, modificare o eliminare un'associazione.</p><p>Il tipo viene impostato automaticamente in base al dominio configurato: gli indirizzi del dominio Armaereo sono funzionali, mentre quelli del dominio Difesa NC sono personali. Per gli altri domini rimane valida la tipologia selezionata.</p><p>Prima dell'inserimento è possibile selezionare <strong>Verifica disponibilità</strong>. Se l'indirizzo è già assegnato, la pagina mostra i nominativi interessati. Il comando <strong>Trasferisci e assegna</strong>, dopo un'ulteriore conferma, rimuove la casella dalle persone indicate e la assegna alla persona corrente.</p><p>Una casella funzionale o condivisa può normalmente essere associata a più persone; utilizzare quindi il trasferimento soltanto quando si vuole effettivamente revocare tutte le associazioni precedenti. Prima dell'eliminazione viene richiesta una conferma.</p></section>
  <section id="incarichi" class="card detail-section anchor-section"><h2>Incarichi e storico</h2><p>La sezione <strong>Incarichi</strong> presenta gli incarichi attualmente associati alla persona, l’eventuale incarico principale, la data iniziale e l’articolazione organizzativa. Lo <strong>Storico incarichi</strong> contiene esclusivamente gli incarichi effettivi conclusi con le relative date.</p><p><strong>Non assegnato</strong> è un segnaposto utilizzato soltanto quando la persona attiva non ha incarichi effettivi. Può essere modificato e trasformato direttamente in un incarico effettivo, ma non può essere chiuso. In alternativa, inserendo un nuovo incarico effettivo, il sistema elimina automaticamente il segnaposto senza trasferirlo nello storico.</p><p>Il comando <strong>Modifica</strong> aggiorna il record selezionato. Quando si inserisce o modifica un incarico diverso da <strong>Non assegnato</strong>, l'ufficio di primo livello è obbligatorio; secondo e terzo livello sono facoltativi e vengono proposti in base al livello superiore. Per <strong>Non assegnato</strong> il sistema utilizza automaticamente gli uffici predefiniti configurati. Non è possibile aggiungerlo se esiste già un altro incarico.</p><p>Con <strong>Chiudi</strong> l’incarico effettivo viene trasferito nello storico con la data finale indicata. Se era l’ultimo incarico corrente, il sistema crea automaticamente <strong>Non assegnato</strong>.</p></section>
  <section id="report" class="card detail-section anchor-section"><h2>Report e analisi</h2><p>La sezione Report della pagina principale raccoglie le analisi disponibili:</p><ul><li><strong>IN/OUT</strong>: personale entrato o uscito nell’intervallo temporale selezionato.</li><li><strong>Caselle postali</strong>: associazioni tra indirizzi e personale, assegnazioni multiple, anomalie di dominio e personale attivo senza casella.</li><li><strong>TTOO</strong>: posizioni previste nella tabella organica, consultabili fino al terzo livello organizzativo.</li><li><strong>Consistenza TTOO</strong>: confronto tra organico previsto e personale attivo assegnato.</li><li><strong>FEO</strong>: consistenza effettiva, distribuzione del personale e indicatori riepilogativi per struttura.</li></ul><h3>Report caselle postali</h3><p>Il cruscotto iniziale mostra indirizzi distinti, numero di associazioni, indirizzi assegnati a più persone, anomalie rispetto ai domini configurati e personale attivo senza casella. La ricerca comprende indirizzo, nominativo e uffici; i filtri consentono di scegliere personale militare o civile, stato di servizio e tipo di casella.</p><p>Le viste rapide isolano assegnazioni multiple, anomalie di dominio e associazioni relative a personale non attivo. Selezionando il cognome si apre il profilo; il comando di gestione è disponibile soltanto agli amministratori autorizzati. <strong>Esporta Excel</strong> genera i fogli <code>Associazioni</code> e <code>Senza casella</code> rispettando i filtri applicati.</p><p>Utilizzare filtri e collegamenti rapidi presenti nelle singole pagine per cambiare livello o unità organizzativa. Il titolo del contesto indica sempre la struttura attualmente analizzata.</p></section>
  <section id="esportazioni" class="card detail-section anchor-section"><h2>Esportare in Excel</h2><p>Il pulsante di esportazione nell’elenco personale genera un file Excel rispettando i filtri applicati. Oltre ai dati visibili, il file contiene l’incarico principale e gli uffici di primo, secondo e terzo livello.</p><p>Anche i risultati dei report IN/OUT possono essere scaricati in formato Excel. Se il browser chiede conferma, scegliere di salvare o aprire il file con un programma compatibile con <code>.xlsx</code>.</p></section>
  <section id="sicurezza" class="card detail-section anchor-section"><h2>Dati e sicurezza</h2><p>I dati personali e sensibili devono essere consultati esclusivamente per finalità di servizio. Non condividere schermate, stampe o informazioni con utenti non autorizzati. Al termine dell’attività chiudere il browser o bloccare la sessione Windows.</p></section>
  <section class="card detail-section anchor-section" id="personale-esterno"><h2>Personale esterno</h2><p>Il personale delle ditte esterne dispone di un elenco separato, raggiungibile dalla home page e dall'intestazione. È possibile cercare per nominativo, codice fiscale o ditta, includere i record non attivi, inserire una nuova persona e modificarne ditta, recapiti e uffici di assegnazione fino al terzo livello.</p><p>La disattivazione non elimina definitivamente il record: lo conserva e lo rende consultabile selezionando <strong>Mostra anche i non attivi</strong>.</p></section>
 </div>
</asp:Content>
