<%@ Page Title="Guida utente" Language="C#" MasterPageFile="~/Site.Master" Inherits="WebGestPersV2.HomePage" %>
<asp:Content ID="Title" ContentPlaceHolderID="TitleContent" runat="server">Guida utente</asp:Content>
<asp:Content ID="Main" ContentPlaceHolderID="MainContent" runat="server">
 <a class="back-link" href="Default.aspx">← Torna all’Help</a>
 <div class="page-heading"><p class="eyebrow">Guida per l’utilizzatore</p><h1>Utilizzare WebGestPers</h1><p>Indicazioni essenziali per consultare correttamente le informazioni sul personale.</p></div>
 <nav class="section-nav" aria-label="Argomenti della guida"><a href="#accesso">Accesso</a><a href="#ricerca">Elenco e filtri</a><a href="#organigramma">Unità organizzative</a><a href="#profilo">Profilo</a><a href="#incarichi">Incarichi</a><a href="#report">Report</a><a href="#esportazioni">Esportazioni</a><a href="#sicurezza">Sicurezza</a></nav>
 <div class="guide-content">
  <section id="accesso" class="card detail-section anchor-section"><h2>Accesso all’applicazione</h2><p>L’accesso utilizza l’identità Windows. Le funzioni disponibili dipendono dal livello associato all’utente nella tabella delle autorizzazioni. Se non si dispone del livello necessario viene mostrata la pagina di accesso negato.</p></section>
  <section id="ricerca" class="card detail-section anchor-section"><h2>Elenco, ricerca e filtri</h2><p>Dalla pagina principale selezionare <strong>Apri elenco personale</strong>. L’elenco iniziale comprende il personale con stato di servizio attivo. La ricerca libera consente di individuare una persona per cognome, nome o codice fiscale.</p><p>I filtri permettono di restringere l’elenco per tipo di personale, grado o profilo, forza armata, categorico e altri criteri disponibili. I filtri possono essere combinati; azzerarli per tornare all’elenco completo del personale attivo.</p><p>La colonna <strong>Grado/Profilo</strong> mostra il grado per il personale militare e la sigla del profilo professionale per il personale civile.</p></section>
  <section id="organigramma" class="card detail-section anchor-section"><h2>Personale per unità organizzativa</h2><p>Dalla home selezionare <strong>Personale per unità</strong> per esplorare gli uffici fino al terzo livello. La visualizzazione comprende il personale attivo collocato secondo l’incarico principale; il numero accanto a ogni ufficio indica la consistenza dell’intero ramo.</p><p>È possibile espandere o comprimere le unità, cercare una persona, un incarico o un ufficio e filtrare tra personale militare e civile. Selezionando il nominativo si apre il relativo profilo. Il pulsante <strong>Esporta in Excel</strong> scarica i dati correntemente filtrati, completi dei tre livelli organizzativi.</p></section>
  <section id="profilo" class="card detail-section anchor-section"><h2>Consultare un profilo</h2><p>Selezionare una persona dall’elenco per aprirne il dettaglio. I pulsanti nella parte superiore consentono di raggiungere rapidamente dati generali, dati sensibili, profilo, incarichi, storico incarichi, storico modifiche e note.</p><p>Il profilo militare contiene grado, forza armata, posizione, categoria, ruolo e specialità. Il profilo civile contiene le informazioni di assunzione e il profilo professionale attuale.</p><p>Lo <strong>Storico modifiche</strong> mostra data e ora, campo variato, valori precedente e nuovo e utente che ha effettuato l’operazione.</p></section>
  <section id="incarichi" class="card detail-section anchor-section"><h2>Incarichi e storico</h2><p>La sezione <strong>Incarichi</strong> presenta gli incarichi attualmente associati alla persona, l’eventuale incarico principale, la data iniziale e l’articolazione organizzativa. Lo <strong>Storico incarichi</strong> contiene gli incarichi conclusi con le relative date.</p></section>
  <section id="report" class="card detail-section anchor-section"><h2>Report e analisi</h2><p>La sezione Report della pagina principale raccoglie le analisi disponibili:</p><ul><li><strong>IN/OUT</strong>: personale entrato o uscito nell’intervallo temporale selezionato.</li><li><strong>TTOO</strong>: posizioni previste nella tabella organica, consultabili fino al terzo livello organizzativo.</li><li><strong>Consistenza TTOO</strong>: confronto tra organico previsto e personale attivo assegnato.</li><li><strong>FEO</strong>: consistenza effettiva, distribuzione del personale e indicatori riepilogativi per struttura.</li></ul><p>Utilizzare filtri e collegamenti rapidi presenti nelle singole pagine per cambiare livello o unità organizzativa. Il titolo del contesto indica sempre la struttura attualmente analizzata.</p></section>
  <section id="esportazioni" class="card detail-section anchor-section"><h2>Esportare in Excel</h2><p>Il pulsante di esportazione nell’elenco personale genera un file Excel rispettando i filtri applicati. Oltre ai dati visibili, il file contiene l’incarico principale e gli uffici di primo, secondo e terzo livello.</p><p>Anche i risultati dei report IN/OUT possono essere scaricati in formato Excel. Se il browser chiede conferma, scegliere di salvare o aprire il file con un programma compatibile con <code>.xlsx</code>.</p></section>
  <section id="sicurezza" class="card detail-section anchor-section"><h2>Dati e sicurezza</h2><p>I dati personali e sensibili devono essere consultati esclusivamente per finalità di servizio. Non condividere schermate, stampe o informazioni con utenti non autorizzati. Al termine dell’attività chiudere il browser o bloccare la sessione Windows.</p></section>
 </div>
</asp:Content>
